# Generated by Django 5.0.6 on 2024-07-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wuzzie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_types',
            field=models.CharField(choices=[('footwear', 'Footwear'), ('outerwear', 'Outerwear'), ('jewelry', 'Jewelry'), ('bottom', 'Bottom'), ('eyewear', 'Eyewear'), ('top', 'Top')], max_length=10),
        ),
    ]
