# Generated by Django 5.0.6 on 2024-07-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wuzzie', '0003_alter_item_item_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_types',
            field=models.CharField(choices=[('footwear', 'Footwear'), ('jewelry', 'Jewelry'), ('bottom', 'Bottom'), ('top', 'Top'), ('eyewear', 'Eyewear'), ('outerwear', 'Outerwear')], max_length=10),
        ),
    ]
